name: Example workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Codecov Action
      uses: Atrox/codecov-action@v0.1.3

    - name: Upload coverage to Codecov  
      uses: ./
      with:
        #commenting out token because tokenless uploads are now supported
        #token: ${{secrets.CODECOV_TOKEN}}
        flags: unittest
        name: codecov-1
